name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Please search existing issues before creating a new one to avoid duplicates.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight Checklist
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have checked the documentation and FAQ
          required: true
        - label: I am using the latest version of the app
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open the app
        2. Go to settings
        3. Tap on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened instead
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but app is usable
        - High - Major functionality broken
        - Critical - App crashes or unusable
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: 📱 App Version
      description: What version of the app are you using?
      placeholder: e.g., v1.2.0
    validations:
      required: true

  - type: input
    id: android-version
    attributes:
      label: 🤖 Android Version
      description: What version of Android are you running?
      placeholder: e.g., Android 13, API 33
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: 📱 Device Model
      description: What device are you using?
      placeholder: e.g., Google Pixel 5, Samsung Galaxy S21
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs / Error Messages
      description: Please paste any relevant logs or error messages
      placeholder: Paste logs here...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...